source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '15.0'

target 'Eva' do
  pod 'Live2DSDK', :path => '../Live2DSDK', :modular_headers => true
  pod 'Kingfisher'
  pod 'SnapKit'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'Kingfisher' or target.name == 'SnapKit'
      target.build_configurations.each do |config|
        config.build_settings['OTHER_SWIFT_FLAGS'] = '-no-verify-emitted-module-interface'
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end
