source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '15.0'

target 'Eva' do
  pod 'Live2DSDK', :path => '../Live2DSDK', :modular_headers => true
  pod 'Kingfisher', '~> 8.0'
  pod 'SnapKit', '~> 5.7.0'
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    if target.name == 'Kingfisher'
#      target.build_configurations.each do |config|
#        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
#      end
#    end
#  end
#end
